apiVersion: apps/v1
kind: Deployment
metadata:
  name: lerrigattobot
  labels:
    app: lerrigattobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lerrigattobot
  template:
    metadata:
      labels:
        app: lerrigattobot
    spec:
      containers:
        - name: lerrigattobot
          image: lerrigatto/lerrigattobot:0.1.0
          envFrom:
            - secretRef:
                name: lerrigattobot-secret-1
            - configMapRef:
                name: lerrigattobot-configmap-1
